### ISSUE TITLE
LO.4 Личный кабинет организатора	LO.4.4 Просмотр проектов организатора

### ISSUE THREAD

**Issue by kseniia2673** [volunteers-for-city-projects/volunteers-backend#104]
- [ ] API для подгрузки проектов организатора из БД

**Comment by 1yunker** [comment]
GET api/projects/me/
При обращении к эндпоинту требуется предъявить токен, по нему будут определяться проекты.
Также реализована фильтрация согласно Требованиям.
https://github.com/volunteers-for-city-projects/volunteers-backend/pull/160
