### ISSUE TITLE
R.5.1 и R.5.2 Регистрация волонтера и Регистрация организатора: удаление пользователей которые не активировали аккаунты

### ISSUE THREAD

**Issue by kseniia2673** [volunteers-for-city-projects/volunteers-backend#162]
удаление пользователей из БД которые не активировали аккаунты в течение 24 часов

**Comment by ArtemKAF** [comment]
- задание на проде добавлено для выполнения при помощи celery и celery-beat (каждые 24 часа будут удаляться не активированные пользователи старше, чем 24 часа).
Через 24 часа будут видны первые результаты.

**Comment by ArtemKAF** [comment]
Задача по удалению неактивированных пользователей успешно запускается каждый день в 23-45 по МСК или 20-45 по внутриконтейнерному времени.
