### ISSUE TITLE
P.7 Проекты P.7.2 Фильтрация по проектам

### ISSUE THREAD

**Issue by kseniia2673** [volunteers-for-city-projects/volunteers-backend#177]
- [x] Сделать апи для выдачи всех проектов, которые соответствуют фильтрам

![Image](https://github.com/volunteers-for-city-projects/volunteers-backend/assets/146813902/8cfde42c-864a-44e0-836c-12e8bcc64838)

**Comment by devbkd** [comment]
Примеры использования фильтров в URL:
    - /projects/?categories={id_categories}
    - /projects/?skills={id_skill}
    - /projects/?city={id_city}
    - /projects/?start_datetime=01.01.2023
    - /projects/?end_datetime=31.12.2023
так же можно совмещать фильтры
