### ISSUE TITLE
LO.4 Личный кабинет организатора LO.4.13 Фильтрация проектов по статусу

### ISSUE THREAD

**Issue by kseniia2673** [volunteers-for-city-projects/volunteers-backend#178]
- [ ] фильтрация проектов по статусу

**Comment by Olga-koml** [comment]
Редактирование фильтра. Добавлен фильтр на модерации.

**Comment by Olga-koml** [comment]
https://github.com/volunteers-for-city-projects/volunteers-backend/pull/239
