### ISSUE TITLE
LO.4. Личный кабинет организатора LO.4.10 Просмотр участников проекта

### ISSUE THREAD

**Issue by kseniia2673** [volunteers-for-city-projects/volunteers-backend#194]
- [x] АПИ участников проекта (выдавать список волонтеров, которых приняли на проект)

[Требования](https://docs.google.com/document/d/10LMRxSNO8-eP9NIrTids55OoMpdcuBtiKItsZ2MBalI/edit#heading=h.hvk4gzs6v7xu)

**Comment by 1yunker** [comment]
https://github.com/volunteers-for-city-projects/volunteers-backend/pull/227
