### ISSUE TITLE
LO.4 Личный кабинет организатора LO.4.7 Добавление фотографий в завершенный проект

### ISSUE THREAD

**Issue by kseniia2673** [volunteers-for-city-projects/volunteers-backend#196]
- [ ] Апи добавления фотографий в проект со статусом "Завершен"

После того как статус проекта меняется на "Завершен", организатор может добавить в карточку проекта фотографии проекта.

Фото
Допустимые значения:
- Предусмотрена возможность вставки изображений с локального устройства пользователя
- Возможно загрузить до 10 фотографий

Требования к изображению:
- форматы JPEG, PNG
- не более 20 Мб
- base64

Премодерация не предусмотрена. 

[Требования](https://docs.google.com/document/d/10LMRxSNO8-eP9NIrTids55OoMpdcuBtiKItsZ2MBalI/edit#heading=h.312ebz34dd61)

**Comment by Olga-koml** [comment]
сделано добавление фотографий списком
https://github.com/volunteers-for-city-projects/volunteers-backend/pull/223
