### ISSUE TITLE
Р.7 Проекты Р.7.6 Добавить проект в избранное

### ISSUE THREAD

**Issue by kseniia2673** [volunteers-for-city-projects/volunteers-backend#197]
- [x] АПИ добавления проекта в избранное (после добавления проектов в избранное, они отображаются в ЛК пользователей)
- [x] АПИ удаления проекта из избранного (при повторном клике на сердечко, проект удаляется из избранного)

**Comment by ArtemKAF** [comment]
Огромная просьба уточнить пользователей. В требованиях "краем глаза" видел, что требуется добавление в избранное у Волонтеров и Организаторов. Администраторам тоже нужно реализовать возможность добавлять в избранное?

**Comment by kseniia2673** [comment]
Избранное необходимо у волонтера и организатора (у админа не нужно тк он не пользователь сайта) @ArtemKAF

**Comment by ArtemKAF** [comment]
- добавление в избранное проекта для волонтеров и организаторов реализовано;
- вывод статуса is_favorite True или False, в зависимости от пользователя, который обратился за получением списка проектов работает(точнее должен работать);
Все это нужно тестировать.
