### ISSUE TITLE
LV. 3 Личный кабинет волонтера LV.3.9 Просмотр приглашений в проект (письма на почту)

### ISSUE THREAD

**Issue by kseniia2673** [volunteers-for-city-projects/volunteers-backend#201]
- [x] Реализовать отправку почтовых писем волонтерам, которых приняли на проект

Если организатор нажал кнопку "принять" в заявках на проект, то волонтер становится участником проекта и ему на почту приходит сообщение "Ваша заявка на проект (Название), одобрена"

**Comment by ArtemKAF** [comment]
Реализовано. Нужно тестировать.
