### ISSUE TITLE
Создание черновика с одним обязательным полем name

### ISSUE THREAD

**Issue by DBKai** [volunteers-for-city-projects/volunteers-backend#219]
При попытке отправить POST запрос на адрес /api/projects/draft/ возникают ошибки.
Запрос:
`categories: []
city: null
description: ""
end_date_application: null
end_datetime: null
event_address: null
event_purpose: ""
name: "Это черновик"
organization: 22
organizer_provides: ""
picture: null
project_events: ""
project_tasks: ""
skills: []
start_date_application: null
start_datetime: null`

Ошибки

`{
    "picture": [
        "Это поле не может быть пустым."
    ],
    "event_address": [
        "Это поле не может быть пустым."
    ]
}`

**Comment by Olga-koml** [comment]
исправила

**Comment by Olga-koml** [comment]
https://github.com/volunteers-for-city-projects/volunteers-backend/pull/223
