### ISSUE TITLE
Доп.задача: ограничения для полей в добавление проекта

### ISSUE THREAD

**Issue by kseniia2673** [volunteers-for-city-projects/volunteers-backend#225]
Добавить такие ограничения:

1. Дата проекта

Максимально ограничение 21 день (минимальное у нас стоит 1 день)

2. Дата подачи заявок

Минимум 7 дней, максимум также 21 день

3. Время проекта

 По времени минимально 3 часа, максимально 9 часов

**Comment by Olga-koml** [comment]
3. считаю что невозможно реализовать, так как у нас не расписывает организатор график мероприятия по дням

**Comment by Olga-koml** [comment]
1. сделано минимум 2 часа, максимум 21 день
2. минимум 7 дней, максимум 21 день
3. время в предела 8-22, продолжительность минимум 2 часа, максимум 9 часов
