### ISSUE TITLE
Доп.задача: добавить логику отправки повторной заявки на проект по P.7.4

### ISSUE THREAD

**Issue by kseniia2673** [volunteers-for-city-projects/volunteers-backend#232]
Как в требованиях: 

7. После отправки заявки, кнопка станоится не активной, отправить заявку повторно нельзя
8. Если заявка волонтера отклонена организатором, то кнопка подачи заявки на проект становится снова активной, но при попытке подать заявку снова, появляется модальное окно в котором сказано, что заявку нельзя подать повторно тк она отклонена организатором

- [x] добавить проверку подавал ли участник заявку на проект

- [x] добавить проверку отклонили ли заявку на проект

**Comment by Olga-koml** [comment]
https://github.com/volunteers-for-city-projects/volunteers-backend/pull/239
