### ISSUE TITLE
Доп. задача Валидация адреса проведения мероприятия.

### ISSUE THREAD

**Issue by Popova-Anastasia** [volunteers-for-city-projects/volunteers-backend#237]
- [x] Создать валидацию адреса. 

[Требования](https://docs.google.com/document/d/10LMRxSNO8-eP9NIrTids55OoMpdcuBtiKItsZ2MBalI/edit#bookmark=id.er7zdi2koe8n)

**Comment by 1yunker** [comment]
https://github.com/volunteers-for-city-projects/volunteers-backend/pull/250
