### ISSUE TITLE
R.5 Регистрация: R.5.1 Регистрация волонтера

### ISSUE THREAD

**Issue by kseniia2673** [volunteers-for-city-projects/volunteers-backend#52]
- [x] API регистрации волонтера

**Comment by 1yunker** [comment]
POST /api/volunteers/
{
  "user": {
      "email": "newuser@me.com",
      "first_name": "Иван",
      "second_name": "Иванович",
      "last_name": "Иванов",
      "password": "zxc123qwe"
  },
  "skills": [1, 2],
  "telegram": "@ivanov",
  "date_of_birth": "2000-01-01",
  "phone": "+79001112233",
  "city": 1
}

**Comment by 1yunker** [comment]
https://github.com/volunteers-for-city-projects/volunteers-backend/pull/18
