### ISSUE TITLE
R.5 Регистрация:R.5.2 Регистрация организатора

### ISSUE THREAD

**Issue by kseniia2673** [volunteers-for-city-projects/volunteers-backend#54]
- [x] API регистрации организатора

**Comment by 1yunker** [comment]
POST /api/organizations/
{
    "contact_person": {
        "first_name": "Николай",
        "second_name": "Николаевич",
        "last_name": "Николаев",
        "email": "neworg@org.com",
        "password": "change_me"
    },
    "title": "Новая организация3",
    "ogrn": "1234567890125",
    "phone": "+79043888888",
    "about": "У нас не обижают",
    "city": 1
}

**Comment by 1yunker** [comment]
https://github.com/volunteers-for-city-projects/volunteers-backend/pull/21
