### ISSUE TITLE
LV.3 Личный кабинет волонтера: LV.3.1 Просмотр анкеты волонтера

### ISSUE THREAD

**Issue by kseniia2673** [volunteers-for-city-projects/volunteers-backend#64]
- [x] АПИ для анкеты волонтера (отображение данных волонтера из БД, которые были добавлены при регистрации)

**Comment by devbkd** [comment]
GET .../api/volunteers/{id}/profile/

вернется JSON (данные тестовые). 
{
    "user": {
        "id": 1,
        "user": {
            "first_name": "ВолонтерПервый",
            "second_name": "ВолонтерПервый",
            "last_name": "ВолонтерПервый",
            "role": "volunteer",
            "id": 2,
            "email": "volunteer1@email.com"
        },
        "skills": [
            {
                "id": 2,
                "name": "Коммуникативные навыки "
            },
            {
                "id": 6,
                "name": "Навыки вождения"
            },
            {
                "id": 7,
                "name": "Навыки работы в сфере экологии "
            },
            {
                "id": 4,
                "name": "Навыки работы с компьютером"
            }
        ],
        "telegram": "@tlgrm",
        "photo": "http://127.0.0.1:8000/media/johanna_beautiful_girl_posing_winki.png",
        "date_of_birth": "2000-08-24",
        "phone": "+79563244215",
        "city": 606
    },
    "projects": [
        {
            "name": "ПроектПервый",
            "description": "ПроектПервый",
            "picture": null,
            "start_datatime": "2023-10-25T20:15:22Z",
            "end_datatime": "2023-11-24T14:15:22Z",
            "application_date": "2023-11-04T14:15:22Z",
            "event_purpose": "string",
            "project_tasks": "string",
            "project_events": "string",
            "organizer_provides": "string",
            "organization": 1,
            "city": 500,
            "category": 1,
            "status_project": "open",
            "photo_previous_event": null,
            "participants": null,
            "status_approve": "pending"
        }
    ],
    "project_incomes": [
        {
            "id": 1,
            "status_incomes": "application_submitted",
            "created_at": "2023-10-25T09:14:17.650627Z",
            "project": 1,
            "volunteer": 1
        }
    ]
}
