### ISSUE TITLE
LO.4 Личный кабинет организатора	LO.4.2 Редактирование анкеты организатора

### ISSUE THREAD

**Issue by kseniia2673** [volunteers-for-city-projects/volunteers-backend#73]
- [x] API для редактирования анкеты организатора (при сохранение изменений, данные обновляются в БД и изменяются в отображение анкеты)

**Comment by 1yunker** [comment]
PUT /api/orgamizations/{id}

**Comment by kseniia2673** [comment]
LO.4.2.2 Редактирование профиля организатора (изменение пароля)

- [ ] Апи для изменения пароля

**Comment by 1yunker** [comment]
POST api/auth/change_password/
