### ISSUE TITLE
LO.4 Личный кабинет организатора	LO.4.3 Добавление нового проекта

### ISSUE THREAD

**Issue by kseniia2673** [volunteers-for-city-projects/volunteers-backend#75]
- [x] API для добавления нового проекта (опубликовать проект) @Olga-koml 

- [x] АПИ добавления черновика @Olga-koml

**Comment by devbkd** [comment]
POST /api/projects/
{
    "name": "TestProject",
    "description": "TestTest",
    "picture": null,
    "start_datatime": "2023-10-18T20:10:01Z",
    "end_datatime": "2023-10-25T10:10:05Z",
    "application_date": "2023-10-20T10:10:19Z",
    "event_purpose": "test3",
    "organization": 2,
    "city": 1,
    "category": 2,
    "status_project": "open",
    "photo_previous_event": null,
    "participants": null,
    "status_approve": "pending"
}

**Comment by 1yunker** [comment]
PATCH /api/projects/
{
...
"status_approve": "editing"
}

**Comment by Olga-koml** [comment]
PR https://github.com/volunteers-for-city-projects/volunteers-backend/pull/202

**Comment by Olga-koml** [comment]
Создание проекта POST на api/projects/
Сохранение проекта как черновика POST на api/projects/draft/
