### ISSUE TITLE
LO.4 Личный кабинет организатора	LO.4.6 Просмотр карточки проекта организатора

### ISSUE THREAD

**Issue by kseniia2673** [volunteers-for-city-projects/volunteers-backend#77]
- [x] Апи для просмотра карточки проекта организатора (гет запрос)

**Comment by devbkd** [comment]
GET  .../api/projects/{id}/

вернется:
{
    "name": "string",
    "description": "string",
    "picture": null,
    "start_datatime": "2023-10-24T15:33:40Z",
    "end_datatime": "2023-11-24T15:34:56Z",
    "application_date": "2023-11-04T15:35:08Z",
    "event_purpose": "string",
    "project_tasks": "string",
    "project_events": "string",
    "organizer_provides": "string",
    "organization": 1,  # id  organization.
    "city": 606,           # id city.
    "category": 1,       # category.
    "status_project": "open",
    "photo_previous_event": null,
    "participants": null,
    "status_approve": "pending"
}
