### ISSUE TITLE
LO.4 Личный кабинет организатора	LO.4.9 Просмотр заявок и ответ на заявку волонтера

### ISSUE THREAD

**Issue by kseniia2673** [volunteers-for-city-projects/volunteers-backend#78]
- [x] сделать апи для ответа на заявку волонтера

**Comment by devbkd** [comment]
Созданы два эндпоинта, для приянтия зяавки и отклонения. 
/api/projects/incomes/{id}/accept_incomes/
Меняется статус на "Принята" и добавлется запись в участниках проекта. 
{
  "project": 0, id - проекта 
  "volunteer": 0, id - волонтера
  "status_incomes": "application_submitted" - статус по умолчанию так и должен оставаться.
}
http://127.0.0.1:8000/api/projects/incomes/{id}/reject_incomes/
Меняет статус на "Отклонена". В эндпоинте указываем id заявки.

**Comment by kseniia2673** [comment]
также нужно сделать просмотр всех заявок на проект. связь проект и волонтер
