### ISSUE TITLE
P.7 Проекты	P.7.4 Подать заявку на участие

### ISSUE THREAD

**Issue by kseniia2673** [volunteers-for-city-projects/volunteers-backend#83]
- [x] Апи подачи заявки на участие в проекте

**Comment by devbkd** [comment]
https://github.com/volunteers-for-city-projects/volunteers-backend/actions/runs/6783249710/job/18437088912?pr=155

Разработано API для подачи заявки на участие в проекте.
Волонтер может добавить заявку на участие в проекте.
Волонтер может удалить заявку на участие в проекте, если статус заявки "Заявка подана", пока не приянто или не отклонено.
